version: '3.8'

services:
  services:
  app:
    build: .
    container_name: school_app 
    volumes:
      # Yahan "." ki jagah pura path likhein jo aapne upar 'inspect' se nikala
      - /var/jenkins_home/workspace/school_app:/var/www
    depends_on:
      - db

  nginx:
    build: ./nginx
    container_name: school_nginx
    ports:
      - "8083:80"
    volumes:
      - /var/jenkins_home/workspace/school_app:/var/www
    depends_on:
      - app
    build: ./nginx
    container_name: school_nginx
    ports:
      - "8083:80"
    volumes:
      - .:/var/www          # YE SABSE ZAROORI HAI: Nginx ko bhi code dikhna chahiye
    depends_on:
      - app
  db:
    image: mysql:8.0
    container_name: school_db
    environment:
      MYSQL_DATABASE: sms
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: