version: '3.8'

services:

  app:
    build: .
    container_name: school_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - school_network

  nginx:
    image: nginx:alpine
    container_name: school_nginx
    ports:
      - "8083:80"
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - school_network

  db:
    image: mysql:5.7
    container_name: school_db
    restart: always
    environment:
      MYSQL_DATABASE: sms
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - school_network

volumes:
  db_data:

networks:
  school_network:
    driver: bridge