version: '3.8'

services:
  app:
    build: .
    container_name: school_app
    volumes:
      # Code mount karne ke liye
      - ${APP_PATH:-.}:/var/www
      # Vendor folder ko overwrite se bachane ke liye (Anonymous Volume)
      - /var/www/vendor
    depends_on:
      - db

  nginx:
    build: ./nginx
    container_name: school_nginx
    ports:
      - "8083:80"
    volumes:
      - ${APP_PATH:-.}:/var/www
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: school_db
    environment:
      MYSQL_DATABASE: sms
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: